version: 2

updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
      groups:
          deps:
              dependency-type: 'production'
          deps-dev:
              dependency-type: 'development'
